--------------------------------------------------------------
-- DATABASE DDL SCRIPT
--------------------------------------------------------------

DROP TABLE A2_MEDICAL_DIRECTOR CASCADE CONSTRAINTS;

DROP TABLE A2_NURSE CASCADE CONSTRAINTS;

DROP TABLE A2_ADMINISTRATIVE_STAFF CASCADE CONSTRAINTS;

DROP TABLE A2_DOCTOR CASCADE CONSTRAINTS;

DROP TABLE A2_ANCILLARY_STAFF CASCADE CONSTRAINTS;

DROP TABLE A2_PORTER CASCADE CONSTRAINTS;

DROP TABLE A2_CLEANER CASCADE CONSTRAINTS;

DROP TABLE A2_SALARIED_STAFF CASCADE CONSTRAINTS;

DROP TABLE A2_HOURLY_STAFF CASCADE CONSTRAINTS;

DROP TABLE A2_EMPLOYEE CASCADE CONSTRAINTS;

-- Create a Database table to represent the "EMPLOYEE" entity.
CREATE TABLE A2_EMPLOYEE(
	emp_id	INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name	VARCHAR(30) NOT NULL,
    phone_no	VARCHAR(15) NOT NULL,
	address	VARCHAR(30) NOT NULL,
	staff_category	VARCHAR(30) NOT NULL,
	job_type	VARCHAR(9) NOT NULL,
	gender	VARCHAR(17) NOT NULL,
	email	VARCHAR(30) NOT NULL,
	dob	DATE NOT NULL,
	CONSTRAINT	pk_EMPLOYEE PRIMARY KEY (emp_id)
);

-- Create a Database table to represent the "SALARIED_STAFF" entity.
CREATE TABLE A2_SALARIED_STAFF(
	salaried_staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    emp_id	INTEGER NOT NULL,
    name VARCHAR(30),
	staff_category	VARCHAR(30),
    holiday_rights	INTEGER,
	pension_rights	VARCHAR(30),
	salary	INTEGER,
    CONSTRAINT	pk_SALARIED_STAFF PRIMARY KEY (salaried_staff_id),
	FOREIGN KEY(emp_id) REFERENCES A2_EMPLOYEE(emp_id) ON DELETE CASCADE
);

-- Insert name and staff category into salaried staff
CREATE OR REPLACE TRIGGER salaried_staff_insert_trigger
BEFORE INSERT ON A2_SALARIED_STAFF
FOR EACH ROW
BEGIN
  SELECT name INTO :new.name
  FROM A2_EMPLOYEE
  WHERE emp_id = :new.emp_id;
END;
/

CREATE OR REPLACE TRIGGER salaried_staff_category_insert_trigger
BEFORE INSERT ON A2_SALARIED_STAFF
FOR EACH ROW
BEGIN
  SELECT staff_category INTO :new.staff_category
  FROM A2_EMPLOYEE
  WHERE emp_id = :new.emp_id;
END;
/



CREATE TABLE A2_HOURLY_STAFF(
	hourly_staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    emp_id	INTEGER NOT NULL,
    name VARCHAR(30),
	staff_category	VARCHAR(30),
    holiday_right	INTEGER,
	pension_rights	VARCHAR(30),
	hourly_rates	INTEGER,
	CONSTRAINT	pk_HOURLY_STAFF PRIMARY KEY (hourly_staff_id),
	FOREIGN KEY(emp_id) REFERENCES A2_EMPLOYEE(emp_id) ON DELETE CASCADE
);

-- Insert name and staff category into hourly staff
CREATE OR REPLACE TRIGGER hourly_staff_insert_trigger
BEFORE INSERT ON A2_HOURLY_STAFF
FOR EACH ROW
BEGIN
  SELECT name INTO :new.name
  FROM A2_EMPLOYEE
  WHERE emp_id = :new.emp_id;
END;
/

CREATE OR REPLACE TRIGGER hourly_staff_category_insert_trigger
BEFORE INSERT ON A2_HOURLY_STAFF
FOR EACH ROW
BEGIN
  SELECT staff_category INTO :new.staff_category
  FROM A2_EMPLOYEE
  WHERE emp_id = :new.emp_id;
END;
/

-- Create a Database table to represent the "MEDICAL_DIRECTOR" entity.
CREATE TABLE A2_MEDICAL_DIRECTOR(
	md_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    salaried_staff_id	INTEGER NOT NULL,
	appointment_date	DATE,
	end_date	DATE,
	doctor_id	INTEGER NOT NULL,
    date_of_employment DATE NOT NULL,
    date_of_leaving DATE,
    reason_for_leaving VARCHAR(30),
	UNIQUE(doctor_id),
	CONSTRAINT	pk_MEDICAL_DIRECTOR PRIMARY KEY (md_id),
	FOREIGN KEY(salaried_staff_id) REFERENCES A2_EMPLOYEE(emp_id) ON DELETE CASCADE
);

-- Create a Database table to represent the "NURSE" entity.
CREATE TABLE A2_NURSE(
	nurse_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    salaried_staff_id	INTEGER NOT NULL,
	license_number	VARCHAR(30),
	nurse_type	VARCHAR(30),
	years_of_experience	INTEGER,
    date_of_employment DATE NOT NULL,
    date_of_leaving DATE,
    reason_for_leaving VARCHAR(30),
	CONSTRAINT	pk_NURSE PRIMARY KEY (nurse_id),
	FOREIGN KEY(salaried_staff_id) REFERENCES A2_SALARIED_STAFF(salaried_staff_id) ON DELETE CASCADE
);

-- Create a Database table to represent the "ADMINISTRATIVE_STAFF" entity.
CREATE TABLE A2_ADMINISTRATIVE_STAFF(
	admin_staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    salaried_staff_id	INTEGER NOT NULL,
	job_title	VARCHAR(30),
	job_description	LONG VARCHAR,
	department	VARCHAR(8),
    date_of_employment DATE NOT NULL,
    date_of_leaving DATE,
    reason_for_leaving VARCHAR(30),
	CONSTRAINT	pk_ADMINISTRATIVE_STAFF PRIMARY KEY (admin_staff_id),
	FOREIGN KEY(salaried_staff_id) REFERENCES A2_SALARIED_STAFF(salaried_staff_id) ON DELETE CASCADE
);

-- Create a Database table to represent the "DOCTOR" entity.
CREATE TABLE A2_DOCTOR(
	doctor_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    salaried_staff_id	INTEGER NOT NULL,
	specialization	VARCHAR(30),
	years_of_experience	INTEGER,
	license_number	VARCHAR(30),
	date_of_last_certification	DATE,
    date_of_employment DATE NOT NULL,
    date_of_leaving DATE,
    reason_for_leaving VARCHAR(30),
	CONSTRAINT	pk_DOCTOR PRIMARY KEY (doctor_id),
	FOREIGN KEY(salaried_staff_id) REFERENCES A2_SALARIED_STAFF(salaried_staff_id) ON DELETE CASCADE
);

-- Create a Database table to represent the "ANCILLARY_STAFF" entity.
CREATE TABLE A2_ANCILLARY_STAFF(
	ancillary_staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hourly_staff_id	INTEGER NOT NULL,
	job_title	VARCHAR(30),
	department	VARCHAR(30),
	job_responsibility	LONG VARCHAR,
    date_of_employment DATE NOT NULL,
    date_of_leaving DATE,
    reason_for_leaving VARCHAR(30),
	CONSTRAINT	pk_ANCILLARY_STAFF PRIMARY KEY (ancillary_staff_id),
	FOREIGN KEY(hourly_staff_id) REFERENCES A2_HOURLY_STAFF(hourly_staff_id) ON DELETE CASCADE
);

-- Create a Database table to represent the "PORTER" entity.
CREATE TABLE A2_PORTER(
	porter_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hourly_staff_id	INTEGER NOT NULL,
	job_title	VARCHAR(30),
	job_responsibility	LONG VARCHAR,
    date_of_employment DATE NOT NULL,
    date_of_leaving DATE,
    reason_for_leaving VARCHAR(30),
	CONSTRAINT	pk_PORTER PRIMARY KEY (porter_id),
	FOREIGN KEY(hourly_staff_id) REFERENCES A2_HOURLY_STAFF(hourly_staff_id) ON DELETE CASCADE
);

-- Create a Database table to represent the "CLEANER" entity.
CREATE TABLE A2_CLEANER(
	cleaner_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hourly_staff_id	INTEGER NOT NULL,
	job_title	VARCHAR(30),
	job_responsibility	LONG VARCHAR,
    date_of_employment DATE NOT NULL,
    date_of_leaving DATE,
    reason_for_leaving VARCHAR(30),
	CONSTRAINT	pk_CLEANER PRIMARY KEY (cleaner_id),
	FOREIGN KEY(hourly_staff_id) REFERENCES A2_HOURLY_STAFF(hourly_staff_id) ON DELETE CASCADE
);

--------------------------------------------------------------
-- End of DDL file
--------------------------------------------------------------
